### ISSUE TITLE
Cleanup README

### ISSUE THREAD

**Issue by MrJohnCoder** [Discord-Sharders/eris-sharder#12]
Cleanup the readme, make it more organized and structured.

**Comment by yasirunilan** [comment]
I would like to work on this issue.

**Comment by MrJohnCoder** [comment]
Sure, go ahead and PR any changes and I'll look over them.

**Comment by kodinglife** [comment]
Still open?

**Comment by MrJohnCoder** [comment]
Yep, going to go through all PRs right now but feel free to add any more if you wish.
