### ISSUE TITLE
Eris-sharder logs back in twice

### ISSUE THREAD

**Issue by ParadoxOrigins** [Discord-Sharders/eris-sharder#31]
I've been using eris-sharder in a staging-environment for a month or two now, and recently deployed it to production as well. During the staging period, i noticed quite a few shards disconnections, though eris-sharder re-connected almost instantly so it wasn't an issue.

Two days ago however, sometimes when a shard got disconnected, eris-sharder would reconnect like expected but log in twice

![image](https://user-images.githubusercontent.com/25114435/41780614-852f8b8e-7635-11e8-8205-fffdd8afeac0.png)

(Please ignore the weeb background) 
The circled parts are the logs when the `ready`event is emitted, as you can see, it is emitted two times. 
The resulting issue is that it create two instances of the bot, therefore double commands outputs and such.

After discussing with an other dev using eris-sharder, i learned that they had the same issue, so an issue within my code is unlikely.

So far i could only see the issue happen on staging environment, on a single-sharded bot, the production bot didn't logged in twice (yet, at least).

As it only started happening 2 days ago, i suspect the issue happen when Discord does something wrong and do not properly disconnect the shard, though that's the only lead i have.

**Comment by MrJohnCoder** [comment]
This is something I've been aware of for awhile and have been researching. As of yet, I have been unable to find a way in which I could reproduce it consistently. More information(logs, repro steps) would be greatly appreciated.

**Comment by ParadoxOrigins** [comment]
I'll let the staging bot run continuously and try to get as much data as i can then, hopefully i can find out something useful

**Comment by ParadoxOrigins** [comment]
```
Error: Invalid session
    at WebSocket.ws.onclose (/applications/felix-staging/node_modules/eris/lib/gateway/Shard.js:1624:27)
    at WebSocket.onClose (/applications/felix-staging/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.EventEmitter.emit (domain.js:442:20)
    at WebSocket.emitClose (/applications/felix-staging/node_modules/ws/lib/websocket.js:172:10)
    at TLSSocket.socketOnClose (/applications/felix-staging/node_modules/ws/lib/websocket.js:774:15)
    at TLSSocket.emit (events.js:187:15)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at _handle.close (net.js:598:12)
    at TCP.done [as _onclose] (_tls_wrap.js:387:7)
```

So this is the error i got from logging the `shardDisconnect` event, right after that eris-sharder logged in twice. Additionally:

![image](https://user-images.githubusercontent.com/25114435/41822028-c2c12a42-77e9-11e8-9a0a-6775017c79a9.png)

As you can see, in this context, the shard was already disconnected and the invalid session happend right after it established back the connection.

Hope that helps, i'll be here if you need any more info

**Comment by ParadoxOrigins** [comment]
As the issue occurred two more times, i can confirm it happen only when the re-connection attempt result in an invalid session, i believe it is linked to how eris handle invalid sessions, as it seems to do special things  when it happen.

**Comment by ParadoxOrigins** [comment]
Alright i think i found the issue:

https://github.com/Discord-Sharders/eris-sharder/blob/cab052a72c5859dae809a25259fd1e0169447550/src/sharding/cluster.js#L204


Eris-sharder loads the code when eris emits ready on the bot, `ready` is emitted when all shards are ready and this is the catch, in my case at least: 

-First time the bot is launched, eris emits ready, eris-sharder loads the code, said code adds the event listeners required for the bot to work (`messageCreate` and such) 
-At some point Discord invalidate the shard session, and eris re-identifiy, once the identification is done, eris emits `ready` because all the shards (read as: the only shard) are ready
-Eris-sharder, like a good boy, load the code thinking it's the first time `ready` is emitted

But because all the events listeners added when the code was first loaded are still here, each event listener is now duplicated. Resulting in for example double outputs because there is now two `messageCreate` listener

Now this is only a theory, but it does make sense with my logs, and also explain why it never occured on the production bot, as `ready` is not emitted because there are multiple shards, as only one is disconnected and the others are still up when the disconnected one resume

References:

https://github.com/abalabahaha/eris/blob/539a34210b94346451dcf41a8fd2ab9ef9c2fbcc/lib/gateway/ShardManager.js#L71

https://github.com/abalabahaha/eris/blob/539a34210b94346451dcf41a8fd2ab9ef9c2fbcc/lib/gateway/ShardManager.js#L89

Additional note:
If this theory reveals to be true, that also means eris-sharder users can prevent it by checking if listeners are already set, but as it would kinda be hardcoded fix, it would be better if eris-sharder prevented it imo

**Comment by MrJohnCoder** [comment]
Your theory checks out. This would make a lot of sense and cover some other issues that I’ve been seeing. Thank you so much!!!

**Comment by MrJohnCoder** [comment]
This should now be fixed.
